# Generated by Django 3.0.7 on 2023-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_text', models.TextField()),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
    ]
