# Generated by Django 3.0.7 on 2023-07-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='testimonial_image',
        ),
    ]
