# Generated by Django 3.0.7 on 2023-07-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_testimony_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='team',
            name='google_plus_link',
        ),
    ]
