# Generated by Django 3.0.7 on 2023-07-10 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230710_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='jobdesk',
            field=models.CharField(default=datetime.datetime(2023, 7, 10, 13, 32, 0, 843594, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
