# Generated by Django 3.0.7 on 2023-07-10 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('No_HP', models.CharField(blank=True, max_length=20)),
                ('wedding_id', models.IntegerField()),
                ('Paket', models.CharField(max_length=100)),
                ('Tanggal', models.DateField()),
                ('Alamat', models.CharField(max_length=100)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('proof_file_cash', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('Harga', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(blank=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
                ('Valid', models.BooleanField(default=False)),
                ('Booking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paket', models.CharField(max_length=100)),
            ],
        ),
    ]
