# Generated by Django 3.0.7 on 2023-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230710_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='Nama',
            new_name='first_name',
        ),
    ]
